packages:
  - apps/*
  - packages/*
catalog:
  "@aws-sdk/client-dynamodb": 3.437.0
  "@aws-sdk/lib-dynamodb": 3.437.0
  "@babel/core": ^7.25.2
  "@babel/runtime": ^7.26.0
  "@clerk/clerk-sdk-node": ~4.12.16
  "@eslint/js": ^9.15.0
  "@expo/vector-icons": ^14.0.2
  "@ianvs/prettier-plugin-sort-imports": ^4.4.0
  "@react-navigation/native": ^7.0.0
  "@sentry/aws-serverless": ~8.7.0
  "@sentry/esbuild-plugin": ~2.10.2
  "@sentry/profiling-node": ~1.2.6
  "@testing-library/react-native": ^12.8.1
  "@tonnant/db": "*"
  "@tonnant/shared": "*"
  "@trpc/server": 11.0.0-alpha-next-2023-11-11-17-32-01.100
  "@types/aws-lambda": ~8.10.125
  "@types/jest": ^29.5.14
  "@types/jsonwebtoken": ^9.0.4
  "@types/lodash": ~4.14.201
  "@types/lodash-es": ~4.17.12
  "@types/react": ~18.3.12
  aws-lambda: ~1.0.7
  d3-dsv: "2"
  date-fns: ~3.6.0
  dotenv: ~16.4.3
  dynamodb-toolbox: ^1.13.4
  eslint: ^9.15.0
  eslint-plugin-react: ^7.37.2
  expo: ~52.0.7
  expo-audio: ~0.2.4
  expo-av: ~15.0.1
  expo-dev-client: ~5.0.4
  expo-font: ~13.0.1
  expo-linking: ~7.0.2
  expo-router: ~4.0.6
  expo-splash-screen: ~0.29.11
  expo-status-bar: ~2.0.0
  expo-system-ui: ~4.0.3
  expo-web-browser: ~14.0.1
  globals: ^15.12.0
  jest: ^29.2.1
  jest-expo: ~52.0.2
  lodash-es: ~4.17.21
  openai: ^4.73.1
  prettier: ^3.3.3
  prettier-plugin-tailwindcss: ^0.6.9
  react: 18.3.1
  react-dom: 18.3.1
  react-native: 0.76.2
  react-native-reanimated: ~3.16.1
  react-native-safe-area-context: 4.12.0
  react-native-screens: ~4.1.0
  react-native-web: ~0.19.13
  replicate: ^1.0.1
  serverless-dotenv-plugin: ~6.0.0
  serverless-esbuild: ~1.54.6
  serverless-lift: ~1.28.1
  serverless-offline: ~13.3.3
  serverless-plugin-aws-alerts: ~1.7.5
  serverless-plugin-monorepo: ~0.11.0
  serverless-plugin-typescript: ~2.1.5
  superjson: 1.13.1
  ts-node: ^10.9.2
  tsx: ^4.19.2
  turbo: 2.3.0
  typescript: ~5.7.2
  typescript-eslint: ^8.15.0
  zod: ^3.23.8
  serverless: 3.37.0
  dotenv-cli: ~7.3.0
  "@t3-oss/env-core": ^0.7.1
